# CUDA and Python 3.11 base image from NVIDIA
FROM nvidia/cuda:11.8.0-cudnn8-runtime-ubuntu22.04

# Install required packages
RUN apt-get update && apt-get install -y \
    wget \
    && rm -rf /var/lib/apt/lists/*

# Install Python 3.11 and pip
RUN apt-get update && \
    apt-get install -y python3.11 python3-pip && \
    ln -s /usr/bin/python3.11 /usr/local/bin/python && \
    python -m pip install --upgrade pip && \
    rm -rf /var/lib/apt/lists/*

# Set the working directory
WORKDIR /workspace

# Install required Python packages
COPY requirements.txt ./
RUN pip install -r requirements.txt

# Set the PATH
ENV PATH /usr/local/bin:$PATH

# Set bash as the default command
CMD ["/bin/bash"]